name: "test"

entrypoint: >-
  python3 train-det.py --device 0 --batch-size 16 --img 640 640 --data coco-det.yaml --cfg cfg/yolov4-pacsp.cfg --weights '' --name yolov4-pacsp --epochs 300
bind_mounts:
  - container_path: /run/determined/coco
    host_path: /home/andrew/coco
  - container_path: /yolo
    host_path: /home/andrew/PyTorch_YOLOv4
resources:
  slots_per_trial: 1
environment:
  image: mendeza/yolov4-env:0.0.2
searcher:
   name: single
   metric: test_loss
   max_length: 1
   
hyperparameters:
   epochs: 5
   batch_size: 64
   test_batch_size: 1000
   learning_rate: 0.0001
   gamma: 0.7
   n_filters1: 8
   n_filters2: 8
   dropout1: 0.2
   dropout2: 0.2

max_restarts: 0